helloworld : helloworld.c
	gcc -o helloworld helloworld.c

clean :
	rm helloworld

hi :
	echo hello~

ping :
	echo pong

list :
	ls -al *.c

backup :
	ls helloworld.c
	cp helloworld.c helloworld_bak.c

everything : hi ping list backup

